# Generated by Django 4.0 on 2021-12-11 19:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='driver_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.driver'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('[А-Я]{2}\\d{4}[А-Я]{2}', "Input number in format 'AЯ1234AБ'")]),
        ),
    ]
